### ISSUE TITLE
LoginSurface is not rendered correctly

### ISSUE THREAD

**Issue by tomalec** [Starcounter/SampleWebsiteTheme#12] opened 2017-09-22 20:51 UTC
### Steps to reproduce
1. Start the app as suggested in README,
2. Compare screenshots with end results

### Expected result
It should look the same
### Actual result
It doesn't

### Technical information
- [ ]  Composition Provider is required - should be mentioned in README,
- [ ] Hard-coded key of composition is outdated - namespaces are now suffixed with `_0`,
- [ ] There is still something missing

##### Involved apps' version

![obraz](https://user-images.githubusercontent.com/17435/30763846-8fc944c8-9fe8-11e7-8d76-ee9af08eb61d.png)

 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari

### Screenshot
![obraz](https://user-images.githubusercontent.com/17435/30763815-533c333a-9fe8-11e7-8ae2-71a4cd173d8d.png)
vs. 
![obraz](https://user-images.githubusercontent.com/17435/30763821-64b6f41a-9fe8-11e7-9b47-522e0e99b635.png)

**Comment by tomalec** [comment] 2017-09-22 20:58
//cc @Mihaiii , @warpech

**Comment by Mihaiii** [comment] 2017-09-28 02:56
I removed my assignment from this issue since the repo is under web-platform-team, but I got to have a look and for [here](https://github.com/StarcounterApps/SampleWebsiteTheme/blob/develop/src/SampleWebsiteTheme/Api/MainHandlers.cs#L46-L47) the catch uri that should be created in line 47 overwrites the catch uri that is created in line 46.

**Comment by warpech** [comment] 2017-10-24 22:09
More accurate steps to reproduce:

1. Checkout `Website`, `Signin`, `SampleWebsiteTheme` develop branch, build and run the apps
2. Go to `http://localhost:8080/signin/signinuser`

## Expected

According to the blending rule declared in https://github.com/Starcounter/SampleWebsiteTheme/blob/ac3198918499a7b8baa3903574eeb91de520d05b/src/SampleWebsiteTheme/Api/MainHandlers.cs#L46, the sign in form should be rendered on LoginSurface

## Actual

It is rendered on DesktopSurface.

@un-tone could you pls investigate this?

**Comment by un-tone** [comment] 2017-10-25 12:21
There is an issue in the `CreateCatchUri` implementation.
The code below rewrites a previous created route https://github.com/Starcounter/SampleWebsiteTheme/blob/ac3198918499a7b8baa3903574eeb91de520d05b/src/SampleWebsiteTheme/Api/MainHandlers.cs#L47

This predicate is not enough, it just returns a first route assigned to the surface
https://github.com/Starcounter/SampleWebsiteTheme/blob/ac3198918499a7b8baa3903574eeb91de520d05b/src/SampleWebsiteTheme/Api/MainHandlers.cs#L141-L142

**Comment by un-tone** [comment] 2017-10-25 12:27
Created PR https://github.com/Starcounter/SampleWebsiteTheme/pull/17

**Comment by un-tone** [comment] 2017-10-26 15:39
Closing as fixed.

**Comment by warpech** [comment] 2017-10-26 15:48
Thanks @un-tone for making the PR.

Now this works but still does not look like on the screenshot. I will make a PR for that.

**Comment by warpech** [comment] 2017-12-11 16:24
The PR was created and merged in https://github.com/Starcounter/SampleWebsiteTheme/pull/18.

**Closed by warpech** 2017-12-11 16:24 UTC

**Comment by warpech** [comment] 2018-01-15 16:41
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/SampleWebsiteTheme/releases/tag/2.1.0
- published in the App Warehouse
